apiVersion: v1
kind: Service
metadata:
  name: redis-service
  
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 6379
  selector:
    name: redis-pod
    app: example-voting-app
