apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: example-voting-app

spec:
  containers:
    - name: nginx-container
      image: prabhavagrawal/vote-app
      ports:
        - containerPort: 80
