apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    name: db-deployment
    app: example-voting-app
    
spec:
  replicas: 1
  selector:
    matchLabels:
      name: db-pod
      app: example-voting-app
  template:
    metadata:
      name: db-pod
      labels:
        name: db-pod
        app: example-voting-app
    spec:
      containers:
        - name: db
          image: postgres:9.4
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
